spring:
  application:
    name: training
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: postgres
    password: postgres
  data:
    rest:
      base-path: api/rest
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8080
